tap "manaflow-ai/cmux"

# CLI ツール
brew "bat"
brew "fd"
brew "fzf"
brew "gh"
brew "hugo"
brew "lazygit"
brew "mise"
brew "neovim"
brew "ripgrep"
brew "starship"
brew "zoxide"
brew "zsh-autosuggestions"

# アプリケーション
cask "alt-tab"
cask "claude"
cask "claude-code"
cask "clipy"
cask "docker-desktop"
cask "dropbox"
cask "flux-app"
cask "google-chrome"
cask "google-japanese-ime"
cask "karabiner-elements"
cask "raycast"
cask "scroll-reverser"
cask "slack"
cask "tableplus"
cask "visual-studio-code"
cask "cmux"
cask "zoom"
