# タップ
tap "k1LoW/tap"
tap "modem-dev/tap"
tap "satococoa/tap"

# CLI ツール
brew "bun"          # herdr-browser プラグインの実行に必要
brew "fd"
brew "fzf"
brew "gh"
brew "herdr"
brew "modem-dev/tap/hunk"
brew "hugo"
brew "jq"          # herdr-unread / git-aicommit が使用
brew "lazydocker"
brew "lazygit"
brew "mise"
brew "k1LoW/tap/mo" # Markdownプレビュー (nvim <leader>m)
brew "neovim"
brew "opencode"
brew "pi-coding-agent"
brew "pipx"         # mise の pipx バックエンド (code-review-graph) に必要
brew "ripgrep"
brew "pure"
brew "zoxide"
brew "tmux"
brew "satococoa/tap/wtp"
brew "zsh-autosuggestions"

# アプリケーション
cask "1password"
cask "1password-cli"
cask "anki"
cask "aqua-voice"
cask "claude"
cask "claude-code"
cask "clipy"
cask "docker-desktop"
cask "dockdoor"
cask "dropbox"
cask "flux-app"
cask "google-chrome"
cask "google-japanese-ime"
cask "karabiner-elements"
cask "raycast"
cask "scroll-reverser"
cask "slack"
cask "tableplus"
cask "tailscale-app"
cask "termius"
cask "visual-studio-code"
cask "ghostty"
cask "zoom"
